[package]
name = "oft"
version = "0.1.0"
description = "Reusable OFT crate for Anchor programs"
edition = "2021"

[lib]
crate-type = [ "lib" ]
name = "oft"

[features]
default = []
idl-build = [ "anchor-lang/idl-build", "anchor-spl/idl-build" ]

[lints.rust.unexpected_cfgs]
level = "allow"
check-cfg = [ "cfg(feature, values(\"anchor-debug\"))" ]

[dependencies]
spl-discriminator = "0.5.2"

[dependencies.anchor-lang]
version = "1.0.2"
features = [ "event-cpi" ]

[dependencies.anchor-spl]
version = "1.0.2"

[dependencies.oft-macros]
path = "macros"

[dependencies.spl-type-length-value]
version = "0.9.1"
features = [ "derive" ]

[dev-dependencies.oapp]
path = "../oapp-solana-contracts"
