//! Trait-like instruction interfaces for Anchor Solana programs.
//!
//! Anchor provides no mechanism for enforcing instruction-level interfaces across programs.
//! This crate introduces **instruction traits**: compile-time enforceable instruction sets
//! with optional default implementations. Each instruction is either **required** (implementor
//! must provide a handler) or **provided** (a default implementation is available).
//!
//! Provided instructions support two override levels:
//!
//! - **Default**: No custom handler defined — the framework emits both the default accounts struct
//!   and an entrypoint that invokes the default handler.
//! - **Override**: Custom handler defined — the framework still emits the default accounts struct
//!   (making it available for composition or reference), but the entrypoint delegates to the custom
//!   handler using whatever context type it declares.
//!
//! See [`README.md`](../README.md) for the full specification.
//!
//! ## Integration steps for a new macro crate
//!
//! 1. Define a `CodegenContext` struct carrying your domain-specific types.
//! 2. Use [`declare_instructions!`] to declare instructions — this generates an enum implementing
//!    [`InstructionSet`] with `all()`, `from_ident()`, `canonical_name()`, and `spec()`.
//! 3. Create an [`OverrideConfig`] with your override attribute and domain names.
//! 4. Wire up the macro entry point following the 4-phase pipeline:
//!    - **Parse**: Attribute args, module, domain types (implementor's responsibility).
//!    - **Collect**: Scan for override handlers with [`InstructionOverrides::collect`].
//!    - **Generate**: Resolve override levels and emit code with [`generate_instructions`].
//!    - **Assemble**: Combine fragments into the final output with [`Assembly::assemble`].

mod assembly;
mod generation;
mod overrides;

pub use assembly::*;
pub use generation::*;
pub use overrides::*;

/// Trait implemented by each macro crate's instruction name enum.
///
/// Generated by [`declare_instructions!`] or implemented manually.
pub trait InstructionSet: Copy + Ord + 'static {
    /// The domain-specific codegen context type (e.g. `CodegenContext`).
    type Ctx;

    /// All known instruction variants in deterministic order.
    fn all() -> &'static [Self];
    /// Parses an instruction name from an attribute argument ident.
    fn from_ident(ident: &syn::Ident) -> Option<Self>;
    /// The canonical function name for this instruction (e.g. `"set_peer"`).
    fn canonical_name(&self) -> &'static str;
    /// Returns the code generation spec for this instruction variant.
    fn spec(self, ctx: &Self::Ctx) -> InstructionSpec<Self::Ctx>;
}

/// Declares all instructions in one place, generating a named enum
/// implementing [`InstructionSet`].
///
/// Each `Variant => mod_name` pair maps an enum variant to a module whose
/// `spec()` function provides the codegen descriptor. Each `mod_name` must
/// be unique — two variants on the same module emit colliding entrypoints.
///
/// Appending `(ctx)` after `mod_name` routes to `mod_name::spec(&ctx)`
/// with the `CodegenContext` reference; omitting it calls `spec()` with
/// no arguments. The marker token is discarded — `ctx` is convention.
///
/// Callers are responsible for declaring their own `mod` items before
/// invoking this macro.
///
/// # Example
///
/// ```ignore
/// mod accept_default_admin;
/// mod grant_role;
/// mod renounce_role;
///
/// declare_instructions! {
///     name    = RbacInstructionSet;
///     context = CodegenContext;
///
///     AcceptDefaultAdmin => accept_default_admin,
///     GrantRole          => grant_role(ctx),
///     RenounceRole       => renounce_role(ctx),
/// }
/// ```
#[macro_export]
macro_rules! declare_instructions {
    // Helper: dispatch spec call. The marker token (conventionally `ctx`) is a
    // routing sigil — it picks the ctx-passing branch but is otherwise
    // discarded, so any ident inside the parens produces equivalent generated
    // code. Without the marker, `spec()` is called with no arguments.
    (@spec_call $ctx:ident, $mod_name:ident ( $marker:ident )) => {
        $mod_name::spec(&$ctx)
    };
    (@spec_call $ctx:ident, $mod_name:ident) => {
        $mod_name::spec()
    };

    (name = $name:ident; context = $ctx:ident; $( $variant:ident => $mod_name:ident $( ( $ctx_marker:ident ) )? ),+ $(,)?) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
        pub(crate) enum $name {
            $( $variant, )+
        }

        impl $crate::InstructionSet for $name {
            type Ctx = $ctx;

            fn all() -> &'static [Self] {
                static ALL: &[$name] = &[
                    $( $name::$variant, )+
                ];
                ALL
            }

            fn from_ident(ident: &syn::Ident) -> Option<Self> {
                match ident.to_string().as_str() {
                    $( stringify!($mod_name) => Some(Self::$variant), )+
                    _ => None,
                }
            }

            fn canonical_name(&self) -> &'static str {
                match self {
                    $( Self::$variant => stringify!($mod_name), )+
                }
            }

            fn spec(self, ctx: &$ctx) -> $crate::InstructionSpec<$ctx> {
                match self {
                    $( Self::$variant => $crate::declare_instructions!(@spec_call ctx, $mod_name $( ( $ctx_marker ) )? ), )+
                }
            }
        }
    };
}
