[package]
name = "example-composer"
version = "0.0.1"
description = "Example program for integration-testing the #[composer] macro"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "example_composer"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "oapp/idl-build"]
custom-heap = []
custom-panic = []
anchor-debug = []

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = [
    "cfg(feature, values(\"anchor-debug\"))",
    "cfg(target_os, values(\"solana\"))",
] }

[dependencies]
anchor-lang = { version = "1.0.2", features = ["init-if-needed"] }
oapp = { path = "../../../dependencies/oapp-solana-contracts" }
