[package]
name = "oapp-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
default = []
idl-build = [ "anchor-lang/idl-build" ]

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
darling = "0.20"
sha2 = "0.10"

[dependencies.anchor-lang]
version = "1.0.2"

[dependencies.anchor-trait]
path = "../../framework-solana-anchor-trait"

[dependencies.syn]
version = "2.0"
features = [ "full", "parsing", "extra-traits" ]

[dev-dependencies]
trybuild = "1.0"
